### ISSUE TITLE
error source issue

### ISSUE THREAD

**Issue by adamfoneil** [adamfoneil/Dapper.QX#34]
I'm getting some errors in Elmah.io coming from Dapper.QX that I can't trace. I know it's related to a date param being out of acceptable range, but I don't know which query:

```
System.Data.SqlTypes.SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at Dapper.QX.Query`1.<>c__DisplayClass18_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dapper.QX.Query`1.ExecuteInnerAsync[T](IDbConnection connection, Func`3 dapperMethod, ILogger logger, Action`1 setParams, Int32 newPageSize)
```

The issue herre is to add some detail to the error message that will help trace where this is coming from.

**Comment by adamfoneil** [comment]
fixed with aa8e0e36dbb6e9093aa7bba562e9d800c0052e84
